### ISSUE TITLE
Confused with Common Settings for Event Hub

### ISSUE THREAD

**Issue by shizhMSFT** [Microsoft/elk-acs-kubernetes#19]
In the step 6 of Instructions, a link should be add to deploy a new event hub if the user does not have one. 

The step
> `List of event hubs` - event hub `ENTITIES` find `Event Hubs` list the event hubs from which you'd pull events e.g. "insights-logs-networksecuritygroupevent,insights-logs-networksecuritygrouprulecounter".

confused me that I thought `insights-logs-networksecuritygroupevent,insights-logs-networksecuritygrouprulecounter` is a single event hub, not two separate event hubs `insights-logs-networksecuritygroupevent` and `insights-logs-networksecuritygrouprulecounter`.

**Comment by yuwzho** [comment]
#28
