### ISSUE TITLE
Can't access this application

### ISSUE THREAD

**Issue by shizhMSFT** [Microsoft/elk-acs-kubernetes#30]
![image](https://user-images.githubusercontent.com/32161882/33926372-c97e8b4a-e018-11e7-9297-d6bee06616e2.png)

# shizh-oss 

## You can't access this application 
shizh-oss needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it.

**Comment by shizhMSFT** [comment]
Additional technical information:
--
Correlation ID: 8471b8ad-1c18-4225-97c2-7cb7bb86baf4
Timestamp: 2017-12-13 07:15:41Z
AADSTS90094: The grant requires admin permission.

**Comment by kenans** [comment]
+1 same issue
