### ISSUE TITLE
How do I check that event hubs is sending messages?

### ISSUE THREAD

**Issue by cwhd** [Microsoft/elk-acs-kubernetes#46]
This may seem like a dumb question; I know elasticsearch fairly well but am still ramping up on k8s.  Now that everything is up and running I have an event hub that I referenced in the setup, but when I go to Kibana I'm not sure what the index is.  Since eleasticsearch is an internal service to k8s I'm not sure how to get in and check it?  If there is some documentation or something you can point me to I would appreciate it. #

**Comment by yaweiw** [comment]
@cwhd, if you provided event hub info in your deployment, the logstash plugin for event hub will be installed. The plugin will start to pull events out of list of event hubs with the interval you set once logstash pod is online. You need to go to Kibana and define your index pattern - default is "logstahs-*", change it to "wad" see if "Create" button is validated. If not, means there are no events in your event hubs yet. [logstash plugin for azureeventhub](https://github.com/Azure/azure-diagnostics-tools/tree/master/Logstash/logstash-input-azureeventhub)

**Comment by yaweiw** [comment]
@cwhd, we've just updated README.

**Comment by cwhd** [comment]
Cool, I got it.  One thing I did wrong was to use the key of the instance of event hub, not the master key, for example RootManageSharedAccessKey.  Once I fixed that I can see the logs coming through logstash.  Thanks!
