### ISSUE TITLE
Event hub message format?

### ISSUE THREAD

**Issue by cwhd** [Microsoft/elk-acs-kubernetes#48]
I have the system hooked up and working and I'm trying to get events from event hub through logstash and visualized in Kibana.  The messages are flowing through, I can see the logs in logstash and there aren't errors.  However when I go into Kibana the fields from the message I sent aren't there.  For example the content of the message I'm sending to event hub is something like this: { "field1":"value", "field2":"value" }.  Logstash parses the JSON but then in Kibana if I delete the index and recreate it field1 and field 2 aren't there.  I looked through the documentation for the event hub WAD plugin but it's not very detailed.  Is there some kind of format I need to change my message to so the fields are indexed and visible in Kibana?

**Comment by yaweiw** [comment]
the logstash plugin for eventhub is meant for Azure Diagnostic events - which presumes to have well defined schema used by the plugin. You can try to stream wad events to event hubs and see if all the fields are visible in kibana. Reference: https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-stream-diagnostic-logs-to-event-hubs.

You can also post related questions to:
https://github.com/Azure/azure-diagnostics-tools/tree/master/Logstash/logstash-input-azureeventhub
