### ISSUE TITLE
Consider support for Azure Service Fabric

### ISSUE THREAD

**Issue by MedAnd** [Microsoft/elk-acs-kubernetes#49]
Any possibility of supporting Azure Service Fabric as an orchestrator? I have numerous Azure Service Fabric and Elastic Search clusters which could be amalgamated (cost saving) if this was supported.

**Comment by yaweiw** [comment]
The solution focuses on how to easily deploy Elastic stack (ELK) on K8s with features like AAD auth integration and WAD events ingestion. AKS (ACS / Kubernetes) is the natural option that provides the infra needed for the deployment. ASF is a different thing. What we want to deploy in the solution isn't common workload on ASF - ASF is more Paas offering on Azure.

**Comment by MedAnd** [comment]
Hi @yaweiw, what I'm hoping for in the ARM template experience via the Azure portal is a drop down which allows me to select K8/ACS/ASF as the cluster/docker orchestrator. 

I assume this should be possible as K8/ACS/ASF all support docker and compose... currently I am forced into having an ASF cluster and an ES Linux VM cluster, and maybe a K8 cluster for highly available PostgreSQL... ideally I want to amalgamate.

Maybe this ASF [request](https://github.com/Azure/service-fabric-issues/issues/705 ) will make this possible...

**Comment by yaweiw** [comment]
@MedAnd I get what you mean and technically it's doable. However they are completely different things in terms of implementation. Having them in the same solution isn't the best design. In fact, we don't even think running Elastic stack on ASF is the right way. AKS is always the top of mind when deploying immutable containers on Azure. 
For log shipping/consumption, a public endpoint is exposed so you are free to ship logs to our solution even they are physically sitting in different clusters on different orchestrators.

**Comment by MedAnd** [comment]
Hi @yaweiw, will close this request but very interested in hearing your thinking re: above.
