### ISSUE TITLE
Adhere to the Elastic brand guidelines for Azure Marketplace logo

### ISSUE THREAD

**Issue by russcam** [Microsoft/elk-acs-kubernetes#50]
[Elastic's brand guidelines](https://www.elastic.co/brand) ask that users not create any modified versions of the logos or change the colours and dimensions, amongst other guidelines.

It'd also be awesome if you could [change the logo on the Azure Marketplace](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/visualstudiochina.elk-on-kube?tab=Overview):

![screenshot 2018-01-15 13 20 28](https://user-images.githubusercontent.com/208231/34924380-120a6bac-f9f7-11e7-851a-34a2d3cd4a05.png)

to adhere to these guidelines

Thanks!

**Comment by yaweiw** [comment]
@russcam we'll take a look. thanks for pointing it out.

**Comment by yuwzho** [comment]
It is resolved: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/visualstudiochina.elk-on-kube?tab=Overview
