### ISSUE TITLE
Deploy failed on azure!

### ISSUE THREAD

**Issue by rddevops** [Microsoft/elk-acs-kubernetes#52]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"Conflict\",\r\n \"message\": \"{\\r\\n \\\"status\\\": \\\"Failed\\\",\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"DeploymentFailed\\\",\\r\\n \\\"message\\\": \\\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"Conflict\\\",\\r\\n \\\"message\\\": \\\"{\\\\r\\\\n \\\\\\\"status\\\\\\\": \\\\\\\"Failed\\\\\\\",\\\\r\\\\n \\\\\\\"error\\\\\\\": {\\\\r\\\\n \\\\\\\"code\\\\\\\": \\\\\\\"ResourceDeploymentFailure\\\\\\\",\\\\r\\\\n \\\\\\\"message\\\\\\\": \\\\\\\"The resource operation completed with terminal provisioning state 'Failed'.\\\\\\\",\\\\r\\\\n \\\\\\\"details\\\\\\\": [\\\\r\\\\n {\\\\r\\\\n \\\\\\\"code\\\\\\\": \\\\\\\"VMExtensionProvisioningError\\\\\\\",\\\\r\\\\n \\\\\\\"message\\\\\\\": \\\\\\\"VM has reported a failure when processing extension 'config-app'. Error message: \\\\\\\\\\\\\\\"Enable failed: failed to execute command: command terminated with exit status=100\\\\\\\\n[stdout]\\\\\\\\n .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)\\\\\\\\r\\\\\\\\ndebconf: falling back to frontend: Teletype\\\\\\\\r\\\\\\\\noracle-license-v1-1 license has already been accepted\\\\\\\\r\\\\\\\\nUnpacking oracle-java8-installer (8u151-1~webupd8~0) ...\\\\\\\\r\\\\\\\\nProcessing triggers for mime-support (3.59ubuntu1) ...\\\\\\\\r\\\\\\\\nProcessing triggers for shared-mime-info (1.5-2ubuntu0.1) ...\\\\\\\\r\\\\\\\\nSetting up java-common (0.56ubuntu2) ...\\\\\\\\r\\\\\\\\nSetting up locales (2.23-0ubuntu10) ...\\\\\\\\r\\\\\\\\ndebconf: unable to initialize frontend: Dialog\\\\\\\\r\\\\\\\\ndebconf: (TERM is not set, so the dialog frontend is not usable.)\\\\\\\\r\\\\\\\\ndebconf: falling back to frontend: Readline\\\\\\\\r\\\\\\\\ndebconf: unable to initialize frontend: Readline\\\\\\\\r\\\\\\\\ndebconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)\\\\\\\\r\\\\\\\\ndebconf: falling back to frontend: Teletype\\\\\\\\r\\\\\\\\nGenerating locales (this might take a while)...\\\\\\\\r\\\\\\\\nGeneration complete.\\\\\\\\r\\\\\\\\nSetting up oracle-java8-installer (8u151-1~webupd8~0) ...\\\\\\\\r\\\\\\\\ndebconf: unable to initialize frontend: Dialog\\\\\\\\r\\\\\\\\ndebconf: (TERM is not set, so the dialog frontend is not usable.)\\\\\\\\r\\\\\\\\ndebconf: falling back to frontend: Readline\\\\\\\\r\\\\\\\\ndebconf: unable to initialize frontend: Readline\\\\\\\\r\\\\\\\\ndebconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)\\\\\\\\r\\\\\\\\ndebconf: falling back to frontend: Teletype\\\\\\\\r\\\\\\\\nNo /var/cache/oracle-jdk8-installer/wgetrc file found.\\\\\\\\r\\\\\\\\nCreating /var/cache/oracle-jdk8-installer/wgetrc and\\\\\\\\r\\\\\\\\nusing default oracle-java8-installer wgetrc settings for it.\\\\\\\\r\\\\\\\\nDownloading Oracle Java 8...\\\\\\\\r\\\\\\\\n--2018-01-18 07:16:12-- http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz\\\\\\\\r\\\\\\\\nResolving download.oracle.com (download.oracle.com)... 2.18.227.187\\\\\\\\r\\\\\\\\nConnecting to download.oracle.com (download.oracle.com)|2.18.227.187|:80... connected.\\\\\\\\r\\\\\\\\nHTTP request sent, awaiting response... 302 Moved Temporarily\\\\\\\\r\\\\\\\\nLocation: https://edelivery.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz [following]\\\\\\\\r\\\\\\\\n--2018-01-18 07:16:12-- https://edelivery.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz\\\\\\\\r\\\\\\\\nResolving edelivery.oracle.com (edelivery.oracle.com)... 72.246.145.28, 2a02:26f0:6b:294::2d3e, 2a02:26f0:6b:291::2d3e\\\\\\\\r\\\\\\\\nConnecting to edelivery.oracle.com (edelivery.oracle.com)|72.246.145.28|:443... connected.\\\\\\\\r\\\\\\\\nHTTP request sent, awaiting response... 302 Moved Temporarily\\\\\\\\r\\\\\\\\nLocation: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz?AuthParam=1516259892_fa5f466669485fa8b4880bf85c5e37c2 [following]\\\\\\\\r\\\\\\\\n--2018-01-18 07:16:13-- http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz?AuthParam=1516259892_fa5f466669485fa8b4880bf85c5e37c2\\\\\\\\r\\\\\\\\nConnecting to download.oracle.com (download.oracle.com)|2.18.227.187|:80... connected.\\\\\\\\r\\\\\\\\nHTTP request sent, awaiting response... 404 Not Found\\\\\\\\r\\\\\\\\n2018-01-18 07:16:13 ERROR 404: Not Found.\\\\\\\\r\\\\\\\\n\\\\\\\\r\\\\\\\\ndownload failed\\\\\\\\r\\\\\\\\nOracle JDK 8 is NOT installed.\\\\\\\\r\\\\\\\\ndpkg: error processing package oracle-java8-installer (--configure):\\\\\\\\r\\\\\\\\n subprocess installed post-installation script returned error exit status 1\\\\\\\\r\\\\\\\\nErrors were encountered while processing:\\\\\\\\r\\\\\\\\n oracle-java8-installer\\\\\\\\r\\\\\\\\n\\\\\\\\u001b[91mW\\\\\\\\u001b[0m\\\\\\\\u001b[91m: \\\\\\\\u001b[0m\\\\\\\\u001b[91m--force-yes is deprecated, use one of the options starting with --allow instead.\\\\\\\\u001b[0m\\\\\\\\u001b[91m\\\\\\\\n\\\\\\\\u001b[0m\\\\\\\\u001b[91mE\\\\\\\\u001b[0m\\\\\\\\u001b[91m: \\\\\\\\u001b[0m\\\\\\\\u001b[91mSub-process /usr/bin/dpkg returned an error code (1)\\\\\\\\u001b[0m\\\\\\\\u001b[91m\\\\\\\\n\\\\\\\\u001b[0m\\\\\\\\n[stderr]\\\\\\\\ngpg: requesting key 417A0893 from hkp server packages.microsoft.com\\\\\\\\ngpg: key 417A0893: public key \\\\\\\\\\\\\\\"MS Open Tech <interop@microsoft.com>\\\\\\\\\\\\\\\" imported\\\\\\\\ngpg: Total number processed: 1\\\\\\\\ngpg: imported: 1 (RSA: 1)\\\\\\\\ndebconf: unable to initialize frontend: Dialog\\\\\\\\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\\\\\\\\ndebconf: falling back to frontend: Readline\\\\\\\\ndebconf: unable to initialize frontend: Readline\\\\\\\\ndebconf: (This frontend requires a controlling tty.)\\\\\\\\ndebconf: falling back to frontend: Teletype\\\\\\\\ndpkg-preconfigure: unable to re-open stdin: \\\\\\\\n % Total % Received % Xferd Average Speed Time Time Time Current\\\\\\\\n Dload Upload Total Spent Left Speed\\\\\\\\n\\\\\\\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\\\\\\\r 0 68.9M 0 514 0 0 1209 0 16:37:15 --:--:-- 16:37:15 1209\\\\\\\\r100 68.9M 100 68.9M 0 0 63.9M 0 0:00:01 0:00:01 --:--:-- 63.9M\\\\\\\\n % Total % Received % Xferd Average Speed Time Time Time Current\\\\\\\\n Dload Upload Total Spent Left Speed\\\\\\\\n\\\\\\\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\\\\\\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\\\\\\\r100 14.3M 100 14.3M 0 0 28.9M 0 --:--:-- --:--:-- --:--:-- 28.9M\\\\\\\\n % Total % Received % Xferd Average Speed Time Time Time Current\\\\\\\\n Dload Upload Total Spent Left Speed\\\\\\\\n\\\\\\\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\\\\\\\r100 35768 0 35768 0 0 134k 0 --:--:-- --:--:-- --:--:-- 135k\\\\\\\\nAdding password for user aurewalkerelk\\\\\\\\nWARNING! Using --password via the CLI is insecure. Use --password-stdin.\\\\\\\\nThe command '/bin/sh -c add-apt-repository -y ppa:webupd8team/java && apt-get update && echo \\\\\\\\\\\\\\\"oracle-java8-installer shared/accepted-oracle-license-v1-1 select true\\\\\\\\\\\\\\\" | debconf-set-selections && apt-get install -y --force-yes oracle-java8-installer' returned a non-zero code: 100\\\\\\\\n\\\\\\\\\\\\\\\".\\\\\\\"\\\\r\\\\n }\\\\r\\\\n ]\\\\r\\\\n }\\\\r\\\\n}\\\"\\r\\n }\\r\\n ]\\r\\n }\\r\\n ]\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by yaweiw** [comment]
@rddevops which region was your deployment happening? Meanwhile, please take a look at all the resources you've deployed. If you can find a 'controllervm' virtual machine, use your credential ssh connect to it and find the log at /tmp/output.log. Send it thru and we'll take a look for you.

@yuwzho

**Comment by rddevops** [comment]
Hi, the deploy was  done on WestEurope Datacenter.  About the log, there  are  some sensitive  data there, and I cant make them public. Are you looking for something specific from the output.log?

**Comment by yaweiw** [comment]
@rddevops we basically want to see where it stopped and what error is. you can remove sensitive data.

**Comment by rddevops** [comment]
I  have  removed the  key  and  user  name:
enter scripts/run.sh
arg d set with value elk-k8master
arg l set with value westeurope
arg u set with value aurewalkerelk
arg p set with value zXkG7,OZzAk5
arg k set with value 
arg a set with value xjket56qnuv7qregistry
arg b set with value OevH9LWHCyV+TA1aEPf0=nnkzV1yrebw
arg j set with value undefined
arg q set with value undefined
arg m set with value undefined
arg n set with value undefined
arg o set with value 4
arg v set with value 10
arg s set with value xjket56qnuv7qdata
arg c set with value Standard_LRS
arg e set with value https://gallery.azure.com/artifact/20161101/visualstudiochina.elk-on-kubepre-release.1.0.0/Artifacts/solution.zip
arg f set with value
arg g set with value BasicAuth
arg h set with value undefined
arg i set with value undefined
arg t set with value undefined
arg w set with value b3af9c6e-23f7-4aac-b59c-3ae24f9bd5aa
arg x set with value WRlWj2r4rgdgAHmFl8zcdp47qjRkijikQnhRsSF5VWw=
arg y set with value f4a9e62b-72ce-41d3-a2d5-a676b2caf86a
arg z set with value ba0c428d-2ca1-4d79-9c6a-2c64a6769013
arg R set with value eu-elk-k8-rg
===================

Re-deploy solution using Azure Container Registry:
run.sh -d   "user" -l westeurope -u aurewalkerelk -p zXkG7,OZzAk5 -k == -a xjket56qnuv7qregistry -b OevH9LWHCyV+TA1aEPf0=nnkzV1yrebw -j undefined -q undefined -m undefined -n undefined -o 4 -v 10 -s xjket56qnuv7qdata -c Standard_LRS -e https://gallery.azure.com/artifact/20161101/visualstudiochina.elk-on-kubepre-release.1.0.0/Artifacts/solution.zip -f  -g BasicAuth -h undefined -i undefined -t undefined -w b3af9c6e-23f7-4aac-b59c-3ae24f9bd5aa -x WRlWj2r4rgdgAHmFl8zcdp47qjRkijikQnhRsSF5VWw= -y f4a9e62b-72ce-41d3-a2d5-a676b2caf86a -z ba0c428d-2ca1-4d79-9c6a-2c64a6769013 -R eu-elk-k8-rg

Re-deploy solution using Custom Registry:
run.sh -d "user" -l westeurope -u aurewalkerelk -p zXkG7,OZzAk5 -k 


masterUrl:  .... .westeurope.cloudapp.azure.com
Login Azure CLI
install kubectl
write private key to private_key
Download K8S credential file
install helm
download templates from https://gallery.azure.com/artifact/20161101/visualstudiochina.elk-on-kubepre-release.1.0.0/Artifacts/solution.zip
expose kubectl proxy at 8080
config nginx for BasicAuth authentication mode
push image to azure container registry: xjket56qnuv7qregistry.azurecr.i

This is everything  from  the logs. Hope helps. But from what i can see from above error the oracle jdk URL is not a valid one anymore.  There is a 302  error.

**Comment by yuwzho** [comment]
I find that the root cause is when building the logstash docker image, installing oracle java sdk failed. Some discussing of the installing failed can be found on [this forum](https://disqus.com/home/discussion/webupd8/install_oracle_java_8_in_ubuntu_via_ppa_jdk8_web_upd8_ubuntu_linux_blog/newest/) and this [bug report](https://bugs.openjdk.java.net/browse/JDK-8195736) according to Oracle website. Seems Oracle removes the 8u151 package forever, but the WebUpd8 team hasn't update there PPA yet.

I will work out a plan for this issue as the P0 task.

**Comment by rddevops** [comment]
Thank you!
